backend:
  name: git-gateway
  preview_context: deploy/netlify
  branch: main
media_folder: public/img
public_folder: img
site_url: https://jonstuebe.com
display_url: https://jonstuebe.com
publish_mode: editorial_workflow
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "posts"
    slug: "{{slug}}"
    preview_path: "post/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
